### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by GARENFEATHER** [theme-next/hexo-theme-next#97] opened 2018-01-30 13:04 UTC
移动端页面左滑可以看得到白边，魅族Pro6手机

**Comment by ivan-nginx** [comment] 2018-01-30 13:05
請用英文寫。

**Comment by GARENFEATHER** [comment] 2018-01-30 13:18
I got that on my mobile phone：

**Comment by GARENFEATHER** [comment] 2018-01-30 13:21
the page look like ↓ on my mobile phone
https://imgchr.com/i/9C15TS

**Comment by GARENFEATHER** [comment] 2018-01-30 13:22
Looks like it doesn't suit my mobile browser?

**Comment by ivan-nginx** [comment] 2018-01-30 13:26
What's browser?

**Comment by ivan-nginx** [comment] 2018-01-30 13:48
Version?

**Comment by GARENFEATHER** [comment] 2018-01-30 14:10
I found both two browsers have this problem↓
Safari：AppleWebKit/603.3.8 Version/10.0 Mobile/14G60 Safari/602.1【useragent data get from WhoIsHostingThis】
Chrome：Chrome 64.0.3282.123

**Comment by ivan-nginx** [comment] 2018-01-30 14:26
![image](https://user-images.githubusercontent.com/16944225/35570923-b3205006-05e1-11e8-9713-dd4538a546fa.png)
U use 5.1.4 version with scheme Pisces.
And on IPhone 6 we see this strange bug:
![image](https://user-images.githubusercontent.com/16944225/35570971-d7ff373e-05e1-11e8-9953-a19f5c591ddc.png)

Here is 6.0.0 version with scheme Pisces on https://rainylog.com
![image](https://user-images.githubusercontent.com/16944225/35571236-933fa7fe-05e2-11e8-8d64-f5c36d8df720.png)
All looks fine as we see.

**Comment by tsanie** [comment] 2018-01-30 14:51
![image](https://user-images.githubusercontent.com/980449/35572626-f7d7ff04-060f-11e8-8a80-533aa663d9ed.png)

The width of the svg was defined to 426, there will be a problem in most mobile layout. I don't know it was generated by which plugin, but maybe the parent div could apply a property `overflow: hidden` to temporarity resolve it.

**Comment by ivan-nginx** [comment] 2018-01-30 14:56
Try to set `width: auto;`

**Comment by GARENFEATHER** [comment] 2018-01-30 15:00
@tsanie even without svg I got this bug too, so it's nothing with svg I think

**Comment by tsanie** [comment] 2018-01-30 15:06
@GARENFEATHER but it seems really the svg problems, try to open http://blog.garenfeather.cn/2018/01/29/test/ and there is no issue with it, and then open http://blog.garenfeather.cn/2018/01/29/stackedit/ it will appear.

And then, try to manual remove the svg element in the html (using the developer tools), the issue would disappear.

**Comment by GARENFEATHER** [comment] 2018-01-30 15:11
Not only my blog,
I try to open https://notes.wanghao.work/, and it has the same problem
I found that it got a big bakground image, maybe sth wrong with that image or we use the same version?

**Comment by tsanie** [comment] 2018-01-30 15:18
The problem is usually caused by an overflow content, and I have got the same problem when I start to use [`hexo-reference`](https://github.com/quentin-chen/hexo-reference).

ps: I can't find the issue in this homepage, could you give me the URL of problem page?

**Comment by tsanie** [comment] 2018-01-30 15:25
Oh, found it, his brand (Doublemine) has a large padding (`0 80px`), and any device that screen width less than 368 will occur the similar problem.

**Comment by GARENFEATHER** [comment] 2018-01-30 20:38
@tsanie yeah, actually you're right, I'v deleted the problem post(with overflow svg) and everything works well now. thx~^_^.
Sorry for replying too late, I was working for adding mermaid support...
And there's still a quick question that...I've heard that NexT has a slack team right? how can I join it to discuss sth related? (😄 yeah I will be really appreciated that if I can be invited...)

**Comment by ivan-nginx** [comment] 2018-01-31 08:37
> I've heard that NexT has a slack team right?

Nope. I heard lie i think.

About join, of course anyone can join. But there is one simple condition: u must want to code, not only to talk. If u will pull some commits and do code better, well, u can join. For now i see only words from u.

***

Also, if issue was solved, need to close it.

**Closed** 2018-01-31 08:36 UTC
