### ISSUE TITLE
Do we need to integrate PWA by default?

### ISSUE THREAD

**Issue by mystic-cg** [theme-next/hexo-theme-next#1287] opened 2019-11-26 01:05 UTC
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
To integrate PWA to the Next by default. 

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: https://developers.google.com/web/tools/workbox/guides/get-started

## Here are some advantages.
FYI.
https://apiumhub.com/tech-blog-barcelona/progressive-web-apps/

**Comment by stevenjoezhang** [comment] 2019-11-26 01:31
Duplicate of https://github.com/iissnan/hexo-theme-next/issues/1790
Run `npm install hexo-pwa`
See https://github.com/lavas-project/hexo-pwa

**Comment by mystic-cg** [comment] 2019-11-26 07:40
Okay

**Closed** 2019-11-26 08:13 UTC
Labels: Invalid, Solved
