### ISSUE TITLE
Refactor `.post-eof` & Siblings

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#759] opened 2019-03-29 18:53 UTC
So, in Muse and Pisces – `.post-eof` enabled.
In Mist – disabled and in Gemini – disabled & implemented with another way.

_Originally posted by @ivan-nginx in https://github.com/theme-next/hexo-theme-next/pull/744/review_comment/create_

**Comment by zq-97** [comment] 2019-03-30 05:00
Report a bug about it, 

in recent update, many unnecessary `important!` is removed, but it cause the extra `post-eof` area under `read more...` button.

![I'm dev - Google Chrome_009](https://user-images.githubusercontent.com/17429111/55271671-a32df100-52eb-11e9-962e-002ff8f11664.png)

![Raincal's Blog - Google Chrome_010](https://user-images.githubusercontent.com/17429111/55271674-a88b3b80-52eb-11e9-9661-66abdcd7aa98.png)

Will this problem be solved in this refactor?

**Comment by 1v9** [comment] 2019-03-30 05:29
@zq-97 Confirmed, this is because new added [hide()](https://github.com/theme-next/hexo-theme-next/blob/master/source/css/_mixins/base.styl#L71) don't contain `!important`

**Comment by stevenjoezhang** [comment] 2019-03-30 05:56
@zq-97 Will be fixed in https://github.com/theme-next/hexo-theme-next/pull/744

**Comment by ivan-nginx** [comment] 2019-03-30 11:55
@zq-97 if fixed confirmed, close it please.

**Comment by zq-97** [comment] 2019-03-30 12:09
@ivan-nginx Not  authorized to close this issue because it's not created by me.

**Comment by ivan-nginx** [comment] 2019-03-30 12:11
Well, this issue actually not about that bug, but about another improvement, related to `.post-eof`.

Can u just confirm what your bug is already fixed?

**Comment by zq-97** [comment] 2019-03-30 12:21
I saw this exsited `.post-eof` issue when I was going to report a bug hours ago, so I reported it here.
Anyway now it's confimed fixed.

**Comment by stevenjoezhang** [comment] 2019-04-03 06:26
![屏幕快照 2019-04-03 下午2 25 26](https://user-images.githubusercontent.com/16272760/55457388-5bc1a080-561c-11e9-8a0c-e2611b91af29.png)

Seems no issue here. They are implemented in the same way.

**Comment by ivan-nginx** [comment] 2019-04-03 13:42
In Gemini post separating implemented in another way. So, no need 2 another ways for post separating, need to choose only one.

**Comment by stevenjoezhang** [comment] 2019-04-03 13:48
I'm interested in it. But it's not related to `.post-eof`, right? It's hide in Gemini.

**Comment by ivan-nginx** [comment] 2019-04-03 15:33
> It's hide in Gemini

Exactly! That's why Issue labeled «Improvement Needed», this isn't bug or feature request.

**Comment by stevenjoezhang** [comment] 2019-05-12 16:58
We can use Child and Sibling Selectors to make CSS more clear. Let's discuss it here: #867

**Closed by stevenjoezhang** 2019-05-12 16:58 UTC
Labels: Improvement Need, Low Priority
