### ISSUE TITLE
sidebar_width Set failure.and CSS abnormality in the sidebar. [sidebar_width need to be natural number]

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#294] opened 2018-05-15 03:09 UTC
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![image](https://user-images.githubusercontent.com/8064012/40034443-8df0858a-582f-11e8-9ed7-ba4aebddee58.png)
No line

and 
```
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 65%
```
The display width is 65%
### Actual behavior 
![image](https://user-images.githubusercontent.com/8064012/40034477-b5de5d74-582f-11e8-87a1-2e6bcf8f81eb.png)
Line display

and 
```
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 65%
```
Default value, 75%
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v
v8.10.0

npm -v
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-leancloud-counter-security": "^1.2.0",
    "hexo-neat": "^1.0.4",
    "hexo-related-popular-posts": "^3.0.1",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.3.2"
  }
}

```

#### Hexo version

```
hexo: 3.6.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 65%
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 65%
```

**Comment by sli1989** [comment] 2018-05-15 04:00
`sidebar_width` need to be a number.

https://github.com/theme-next/hexo-theme-next/blob/03bd4b4537a5eb1258d8b3580ff6246459ad8f4a/source/css/_variables/Gemini.styl#L10-L11

The line isn't shown in your live blog? I can't reproduce it. Can you provide a live demo?

**Comment by sli1989** [comment] 2018-05-15 07:29
I see, but there is no lines in sidebar.

**Comment by aixiu** [comment] 2018-05-15 07:36
Slide the mouse in the sidebar.
![image](https://user-images.githubusercontent.com/8064012/40042995-ba792208-5855-11e8-9911-730b151eae55.png)

**Comment by sli1989** [comment] 2018-05-15 07:43
yes, i did in ie/edge/chrome, there is no line.

**Comment by aixiu** [comment] 2018-05-15 07:47
The Chrome I used.
![11](https://user-images.githubusercontent.com/8064012/40043484-27accd2e-5857-11e8-9dd3-38e14531d942.gif)
Mozilla Firefox no line.

**Comment by sli1989** [comment] 2018-05-15 07:50
I don't know why, i am fine in chrome.
The screenshots of F12 to see the elements? Other guys may helpful.

**Comment by aixiu** [comment] 2018-05-15 07:58
@sli1989 Solved, Ctrl+F5. 
```
# Manual define the sidebar width
# !!Only available for Gemini Scheme currently
# Leave it empty for the default 240
sidebar_width: 65%
```
![image](https://user-images.githubusercontent.com/8064012/40043989-b388fa74-5858-11e8-867d-c64bca983a19.png)
Width setting failure

**Comment by sli1989** [comment] 2018-05-15 08:02
well. if solved, please close the issue.

**Closed** 2018-05-15 08:14 UTC
Labels: Solved
