### ISSUE TITLE
Unable to add external link in Menu items [not supported for now]

### ISSUE THREAD

**Issue by ylbeethoven** [theme-next/hexo-theme-next#393] opened 2018-08-22 11:40 UTC
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).This webpage is under construction
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
After click "main blog" in menu, it will redirect the page to www.example.com

### Actual behavior
It will redirect to www.myhexoblog.com/www.example.com

### Steps to reproduce the behavior 
set the menu as below
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  #categories: /categories/ || th
  archives: /archives/ || archive
  Main Blog: /www.example.com/ || wordpress
* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

v8.11.2
6.4.0

### Package dependencies Information

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-filter-highlight": "0.0.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-scss": "^1.2.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

#### Hexo version

hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.7.0 darwin x64
http_parser: 2.8.0
node: 8.11.2
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.29.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**
- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml

```

**Comment by maple3142** [comment] 2018-08-22 11:53
Change `/www.example.com/` into `https://www.example.com/`

**Comment by ylbeethoven** [comment] 2018-08-22 11:58
I've done that as well, it will direct to www.myhexoblog.com/https://www.example.com

**Comment by ivan-nginx** [comment] 2018-08-22 12:16
For now external links only supported for sidebar menu items, not for main menu.

https://github.com/theme-next/hexo-theme-next/blob/79932de3431db6c7a2c306e980dc78e77af4dfb3/_config.yml#L152-L167

So, u can paste here any links u want.

**Comment by ylbeethoven** [comment] 2018-08-22 12:39
OK. Thanks Mate, I guess I can only use side bar to add the external link.

Do  know how to swap position of Menu and Site bar?

Currently menu is on top of side bar.

Thanks

**Comment by sli1989** [comment] 2018-09-02 08:02
> Do know how to swap position of Menu and Site bar?

the position of menu is fixed within different scheme. The functional of changing position is not supported. Any suggestion of new features is welcomed.

If the problem is solved, u can close the issue.

**Closed** 2018-09-16 12:31 UTC
Labels: Question, Solved
