### ISSUE TITLE
Consider to change your template engine.

### ISSUE THREAD

**Issue by sven31316** [theme-next/hexo-theme-next#1161] opened 2019-09-08 13:15 UTC
### I agree and want to create new issue 

- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***
## My recommend
> when I look into you source code ,I find your template engine is **swig** ,which seems to be left unmaintained.  The hexo default theme ,landscape ,is using the template engine of ejs. So I just make a suggestion that we use some other template engine like ejs,pug etc.

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment] 2019-09-08 15:40
Duplicate of https://github.com/theme-next/hexo-theme-next/pull/1068

**Comment by stevenjoezhang** [comment] 2019-09-23 05:47
Besides, `swig-templates` is a dependency of Hexo. You should report it to Hexo team.

> swig ,which seems to be left unmaintained

**Comment by stevenjoezhang** [comment] 2019-10-16 06:44
Superseded by https://github.com/theme-next/hexo-theme-next/issues/1214

**Closed by stevenjoezhang** 2019-10-16 06:44 UTC
Labels: Duplicate, Hexo, Template Engine
