### ISSUE TITLE
Disqus comment count is not shown

### ISSUE THREAD

**Issue by colorfulshark** [theme-next/hexo-theme-next#1324] opened 2019-12-21 15:48 UTC
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.
- [x] I have tried clearing browser cache and executing `hexo clean`, it does not work, the same issue can be reproduced on my laptop and phone.
- [x] I have tried proxy my network globally, seems not work.

***

## Expected behavior 
Comment count is shown on the page.

## Actual behavior 

Comment count is not shown.

- Links to demo site with this issue: https://blog.colorfulshark.net/
- Links to repository or source code of the blog: https://github.com/colorfulshark/colorfulshark.net

## Steps to reproduce the behavior 
Enable disqus and comment count in next theme, then open site page.

### Node.js and NPM Information

```
v13.0.1
6.12.0
```

### Package dependencies Information

```
hexo-site@0.0.0 /develop/blog/colorfulshark.net
├── hexo@4.0.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-searchdb@1.2.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

### Hexo Configuration

[hexo configuration](https://github.com/colorfulshark/colorfulshark.net/blob/master/_config.yml)

### NexT Configuration

[modified patch](https://github.com/colorfulshark/hexo-theme-next/commit/0e54525ee10efb51b906c6aad88cbe8df13fd1fb)

## Other Information 
The strange part is that some posts does show the comment count, but they seem never get updated, even though I made a comment manually.

**Comment by stevenjoezhang** [comment] 2019-12-22 16:37
![截屏2019-12-23上午12 32 27](https://user-images.githubusercontent.com/16272760/71324628-074cb100-251c-11ea-806f-927280241415.png)
![截屏2019-12-23上午12 32 59](https://user-images.githubusercontent.com/16272760/71324629-07e54780-251c-11ea-8dcd-59ba903be3e2.png)

The comment count of new posts are not loaded. I'm not sure why this problem occurs - it looks like NexT's use of disqus is completely correct:
https://help.disqus.com/en/articles/1717274-adding-comment-count-links-to-your-home-page

**Comment by r12f** [comment] 2020-01-15 03:00
Not sure if this is related to the issue below. When loading the post, the DISQUS.reset function is not getting called, because window.DISQUS is not set at that moment, so the DISQUS server won't have any data for this post / identifier.
![image](https://user-images.githubusercontent.com/1533278/72401033-ce10f680-36ff-11ea-90a4-edee8c51d973.png)

**Comment by stevenjoezhang** [comment] 2020-01-15 04:39
@colorfulshark @r12f Can you checkout this branch: https://github.com/theme-next/hexo-theme-next/tree/disqus
Or cherry-pick this commit: https://github.com/theme-next/hexo-theme-next/commit/5f07016e0ae6481369c60e7c308684d6f7051ccf
To help confirm if the issue is resolved?

**Comment by r12f** [comment] 2020-01-15 05:01
just cherry picked this commit and updated my blog again, but still not working:
![image](https://user-images.githubusercontent.com/1533278/72406387-e5a4ab00-3710-11ea-88c6-fa492ad088a4.png)

here is the page I checked: http://r12f.com/posts/use-azure-pipeline-to-build-npm-package/.

**Comment by stevenjoezhang** [comment] 2020-01-15 07:15
@r12f Can you confirm it again? It seems that disqus is working fine now.

<img width="1375" alt="截屏2020-01-15下午3 10 20" src="https://user-images.githubusercontent.com/16272760/72412882-7038e900-37a9-11ea-8785-fde9757c92d2.png">

Your screenshot shows that `window.DISQUS` is `undefined`, which is actually normal, because at the breakpoint some scripts that related to disqus are not executed

**Comment by r12f** [comment] 2020-01-15 07:59
@stevenjoezhang got it and thanks for checking it again! when I was checking it, it didn't work, but now somehow it works for some posts, but not all. The count list is empty even by checking the raw data from disqus.
![image](https://user-images.githubusercontent.com/1533278/72415388-36c09900-3729-11ea-868f-83dbf1351866.png)
![image](https://user-images.githubusercontent.com/1533278/72415518-712a3600-3729-11ea-99d8-60a97c5d3dd3.png)

I guess it might be fixed by your visit or someone else, but I don't know what triggered disqus to create the record. I tried to login/logout my disqus account and refresh the page, but none of them seems to be helpful as well.

**Comment by stevenjoezhang** [comment] 2020-01-15 08:24
I'm not quite sure about this either, maybe it's the problem of disqus itself. I will merge this fix into the master branch. If this problem persists in the future, please continue to report to us.

**Comment by r12f** [comment] 2020-01-15 08:34
it suddenly works now.... maybe disqus is being really slow processing the visits? i am confused.... maybe I can wait longer after publishing new post next time and see what will happen.

![image](https://user-images.githubusercontent.com/1533278/72416213-05e16380-372b-11ea-88c5-cbac3a568fa4.png)

**Comment by r12f** [comment] 2020-01-15 08:35
@stevenjoezhang yea, sounds great! will do!

**Closed** 2020-01-15 10:48 UTC
Labels: Bug, Solved, ☑ Verified

**Comment by longhengyu** [comment] 2020-07-08 07:12
it works for me locally, but when I deploy hexo to github.io, it doesn't show commend count.
