### ISSUE TITLE
Too large mermaid node size on mobile Chrome

### ISSUE THREAD

**Issue by zq1997** [theme-next/hexo-theme-next#783] opened 2019-04-01 02:38 UTC
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
> Screenshot on Android firefox
![Screenshot_2019-04-01-10-20-12-004_org mozilla fi](https://user-images.githubusercontent.com/17429111/55300277-507a4380-5469-11e9-9841-69e3ca799f8f.png)

### Actual behavior 
> Screenshot on Android chrome
![chrome](https://user-images.githubusercontent.com/17429111/55300292-58d27e80-5469-11e9-98f8-a5049912829f.png)

### Steps to reproduce the behavior 
Try this mermiad code and view it on mobile Chrome
```
graph LR
c-m1(( ))-->c-m2(( ))
c-m2(( ))-->c-m3(( ))
c-m3(( ))-->c-m4(( ))
c-m4(( ))-->c-m5(( ))
c-m5-->m(master)
c-m5-->c-merge1[ ]
c-m3-->c-b1[ ]
c-b1-->b(blog)
c-b1-->c-merge1
c-merge1-->ub(* updated-blog)
```

* Link to demo site with this issue: [https://i-m.dev/posts/20190331-103618.html](https://i-m.dev/posts/20190331-103618.html)

### Node.js and NPM Information

```
v10.15.3
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-directory-category": "^1.0.7",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-heading-index": "^1.0.1",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

**Comment by stevenjoezhang** [comment] 2019-04-01 02:40
NexT is using default configuration of mermaid. Open an issue here would be better: https://github.com/knsv/mermaid

**Comment by zq-97** [comment] 2019-04-01 02:45
> NexT is using default configuration of mermaid. Open an issue here would be better: https://github.com/knsv/mermaid

@stevenjoezhang opened [https://github.com/knsv/mermaid/issues/816](https://github.com/knsv/mermaid/issues/816)

**Comment by stevenjoezhang** [comment] 2019-04-01 02:46
Maybe it's caused by some CSS overwrite? Not sure...

**Comment by zq-97** [comment] 2019-04-01 03:02
@stevenjoezhang I have tried to debug with chrome remote tool and disable serveral CSS attribute to find the cause, but failed.

**Comment by 1v9** [comment] 2019-04-01 03:18
@zq-97 Do you want to join us?

**Comment by zq-97** [comment] 2019-04-01 03:27
> @zq-97 Do you want to join us?

Thank you very much for your invitation but I'm afraid I don't have enough energy to take the responsibilities, for both I'm not a skillful web developer and I don't have much spare time.

**Comment by zq-97** [comment] 2019-04-03 13:59
@stevenjoezhang Comfirmed as third party problem instead of CSS override, because I test the flowing code as standalone html page and this problem still exists
```html
</html>
</body>

<pre class="mermaid">graph LR
    c-m1(( ))-->c-m2(( ))
    c-m2(( ))-->c-m3(( ))
    c-m3---m(master)
    c-m3-->c-b1(( ))
    c-b1---b(* blog)
    style c-m1 fill:red,stroke:none;
    style c-m2 fill:red,stroke:none;
    style c-m3 fill:red,stroke:none;
    style c-b1 fill:green,stroke:none;
</pre>

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script>
    if ($('body').find('pre.mermaid').length) {
        $.ajax({
            type: 'GET',
            url: 'https://cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js',
            dataType: 'script',
            cache: true,
            success: function () {
                mermaid.initialize({
                    theme: 'dark',
                    logLevel: 3,
                    flowchart: {
                        curve: 'linear'
                    },
                    gantt: {
                        axisFormat: '%m/%d/%Y'
                    },
                    sequence: {
                        actorMargin: 50
                    }
                });
            }
        });
    }
</script>

</body>

</html>
```

**Comment by stevenjoezhang** [comment] 2019-04-03 14:05
Can you test another version of mermaid? By default NexT is using 8.0.0, the latest version. Maybe it will work fine in some legacy versions?

**Comment by zq-97** [comment] 2019-04-03 14:13
v7 is the same as v8.    
v6 and lower work but cause other problems (wrong node&line color), and they are quite out of date

**Comment by stevenjoezhang** [comment] 2019-08-27 17:39
@zq1997 Have you encountered this issue: https://github.com/theme-next/hexo-theme-next/issues/863?

If the generated mermaid graph is in `svg` format, can it solve the problem?

**Comment by zq1997** [comment] 2019-08-28 05:40
How to switch to `svg` format?

**Comment by zq1997** [comment] 2019-08-28 14:00
@stevenjoezhang 
![image](https://user-images.githubusercontent.com/17429111/63862440-2bb9d600-c9df-11e9-9e98-2d51e3b0bcfc.png)
[Something](https://i-m.dev/posts/20190313-194446.html) goes wrong with the newest code on `master` branch

**Comment by stevenjoezhang** [comment] 2019-08-28 14:22
Theoretically, mermaid related code has not been modified in the past month...
Maybe you can try creating a test page to see if this code can be executed correctly:
![屏幕快照 2019-08-28 下午10 19 41](https://user-images.githubusercontent.com/16272760/63864218-0d090e80-c9e2-11e9-840a-132eb67afcc1.png)
```
<pre class="mermaid">graph TB
input_tensor((input_tensor ?x32)) --> dense_layer[dense_layer Weight:32x4 bias:4]
dense_layer --> output_tensor((output_tensor ?x4))</pre>
```

**Comment by zq1997** [comment] 2019-08-29 01:53
[https://i-m.dev/test.html](https://i-m.dev/test.html) not works

**Comment by stevenjoezhang** [comment] 2019-09-01 16:28
@zq1997 Seems that this has been fixed by mermaid team?

![63CF34E9-B309-4399-B7FD-5C36E77010E6](https://user-images.githubusercontent.com/16272760/64079292-6e015100-cd18-11e9-88e8-aed587cd33a8.png)
![79D562ED-E858-40C6-9740-09E43668A5BE](https://user-images.githubusercontent.com/16272760/64079293-6e99e780-cd18-11e9-84d6-d40a2cb3a22f.png)
![6D6010A1-F317-4B9A-988D-2968E9332C9A](https://user-images.githubusercontent.com/16272760/64079294-6e99e780-cd18-11e9-9b7c-5fa0950fb6e5.png)

**Comment by zq1997** [comment] 2019-09-02 03:08
好像是mermail不知道哪个版本更新了，不允许图框中的文字出现下划线`_`，出现的话必须要用引号括起来，然后我现在加了引号才修复了。
另外，前面提到的svg模式是怎么开启啊？

**Comment by stevenjoezhang** [comment] 2019-09-02 03:10
我还没研究，`svg`是这里提到的：https://github.com/theme-next/hexo-theme-next/issues/863

**Comment by stevenjoezhang** [comment] 2019-09-02 03:57
所以这个issue似乎已经被mermaid官方解决了？

**Comment by zq1997** [comment] 2019-09-02 05:43
没有，在Android chrome上还是最开始的样子

**Comment by stevenjoezhang** [comment] 2019-09-02 06:26
那感觉是浏览器的锅了，iOS上用几个浏览器测试都正常..

**Comment by stevenjoezhang** [comment] 2019-09-02 06:46
![屏幕快照 2019-09-02 下午2 40 36](https://user-images.githubusercontent.com/16272760/64094955-025aca80-cd90-11e9-97a6-4618c6928916.png)
![屏幕快照 2019-09-02 下午2 42 57](https://user-images.githubusercontent.com/16272760/64094956-025aca80-cd90-11e9-9f25-0983c9b3099d.png)

确认了一下，android firefox都是正常的，就是chrome有问题。只能等官方解决了，但是也没什么进度 https://github.com/knsv/mermaid/issues/816
可以继续到 #863 讨论

**Closed by stevenjoezhang** 2019-09-02 06:46 UTC
Labels: Irrelevant, 🔌 3rd Party Service
