### ISSUE TITLE
本地预览，网页样式无法加载

### ISSUE THREAD

**Issue by FeiyuKevin** [theme-next/hexo-theme-next#536] opened 2018-12-25 17:28 UTC
PS C:\#E\GitTest\feiyukevin.github.io> hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Asset render failed: css/main.css
TypeError: C:/#E/GitTest/feiyukevin.github.io/themes/next/source/css/_variables/base.styl:336:79
   332| hexo-config('note.light_bg_offset') is a 'unit' ? (lbg = unit(hexo-config('note.light_bg_offset'),"%")) : (lbg = 0)
   333|
   334| // Default
   335| $note-default-border        = #777
   336| $note-default-bg            = lighten(spin($note-default-border, 0), 94% + lbg)
--------------------------------------------------------------------------------------^
   337| $note-default-text          = $note-default-border
   338| $note-default-icon          = "\f0a9"
   339|

Cannot read property 'nodes' of undefined

    at Evaluator.vendors (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:1567:32)
    at Evaluator.unvendorize (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:1581:30)
    at Evaluator.visitCall (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:484:24)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitIdent (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:551:22)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.importFile (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:99:18)
    at Evaluator.visitImport (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at visitBody (C:\#E\GitTest\feiyukevin.github.io\node_modules\stylus\lib\visitor\evaluator.js:433:17)

**Comment by FeiyuKevin** [comment] 2018-12-29 19:07
![feiyu](https://user-images.githubusercontent.com/25132486/50541399-171f0700-0be0-11e9-9a79-96d57167a468.png)

<img width="766" alt="2018-12-30_03-00-49" src="https://user-images.githubusercontent.com/25132486/50541364-42552680-0bdf-11e9-99fc-44576bf89439.png">

<img width="236" alt="2018-12-30_03-02-39" src="https://user-images.githubusercontent.com/25132486/50541393-040c3700-0be0-11e9-9243-a3b5a3c1dd18.png">

**Comment by FeiyuKevin** [comment] 2018-12-30 04:46
@stevenjoezhang 这个issue，请您关闭，我已发布new issue，包括详细信息，谢谢~

**Comment by ivan-nginx** [comment] 2018-12-30 05:39
Duplicate of #548.

**Closed by ivan-nginx** 2018-12-30 05:39 UTC
Labels: Need More Info
