### ISSUE TITLE
更新到Hexo 4后，图标显示异常

### ISSUE THREAD

**Issue by WitherZuo** [theme-next/hexo-theme-next#1216] opened 2019-10-16 07:14 UTC
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.  

## Expected behavior 
可以正常显示所有图标

## Actual behavior 

无法正常显示图标（见底部的截图）
- Links to demo site with this issue: 见最底部
- Links to repository or source code of the blog: 见最底部

## Steps to reproduce the behavior 
1. 下载源码文件，解压后安装Hexo 4.0及其它依赖包
2. 运行hexo clean&&hexo s
3. 查看页面

### Node.js and NPM Information

```
node -v  v12.6.0
npm -v  6.12.0
```

### Hexo Version

```
hexo: 4.0.0                                                                                                   
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
node: 12.6.0
v8: 7.5.288.22-node.14
uv: 1.30.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```  

## Other Information   
**Source code:** 
[HexoBlog.zip](https://github.com/theme-next/hexo-theme-next/files/3732902/HexoBlog.zip)

![Snipaste_2019-10-16_14-51-00](https://user-images.githubusercontent.com/25317916/66895968-8dcda980-f026-11e9-80b7-47934d949c97.png)
![Snipaste_2019-10-16_14-50-42](https://user-images.githubusercontent.com/25317916/66895970-8dcda980-f026-11e9-9b39-585e5bba0a02.png)

**Comment by stevenjoezhang** [comment] 2019-10-16 07:27
Duplicate of https://github.com/hexojs/hexo/issues/3729 https://github.com/theme-next/hexo-theme-next/pull/1175

**Closed by stevenjoezhang** 2019-10-16 07:27 UTC
Labels: Bug

**Comment by WitherZuo** [comment] 2019-10-16 11:22
请问，Hexo 4和目前最新的NexT v7.4.1都解决了这个问题吗？更新hexo-util至1.4.0后问题仍然存在

**Comment by stevenjoezhang** [comment] 2019-10-16 11:26
这个 PR 合到7.4.2版本了，您可以等待 NexT发布新版本，或者更新到最新的master分支试试。

**Comment by WitherZuo** [comment] 2019-10-16 11:28
@stevenjoezhang 好，我再等等吧，反正最近拖更严重😂
