### ISSUE TITLE
"RSS" button in V7.3.0

### ISSUE THREAD

**Issue by code004Accepted** [theme-next/hexo-theme-next#1077] opened 2019-08-08 11:34 UTC
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![1234.PNG](https://i.loli.net/2019/08/08/MrIxgNwHVZpbPhc.png)

### Actual behavior 

![123.PNG](https://i.loli.net/2019/08/08/O3Ja9enVf15Yzir.png)

* Link to demo site with this feature: https://code004.ml
* Link(s) to source code or any usefull link(s): N/A

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [X] Gemini

**Comment by stevenjoezhang** [comment] 2019-08-08 12:47
Duplicate of https://github.com/theme-next/hexo-theme-next/pull/1060

**Closed by stevenjoezhang** 2019-08-08 12:47 UTC
