### ISSUE TITLE
Right margin bug in mobile style

### ISSUE THREAD

**Issue by GARENFEATHER** [theme-next/hexo-theme-next#181] opened 2018-03-17 12:19 UTC
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

A right margin style in both mobile and PC mode

### Actual behavior 

![NexT.Pisces](https://media.discordapp.net/attachments/420095259125743637/424539712909475850/c2fbedd5-605b-4207-9782-081d141ab879.jpg?width=169&height=301)

[live demo](http://blog.garenfeather.cn/)

### Steps to reproduce the behavior 
set theme `_config.yml`
1. `mobile_layout_economy: true`
2. ~~excerpt_description: true~~
   `auto_excerpt: enable: true`
3. use `<!— more —>` tag in my post

* Link to demo site with this issue: [here](http://blog.garenfeather.cn/)
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

nothing wrong

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.7"
  },
  "dependencies": {
    "crypto": "^1.0.1",
    "fs": "0.0.1-security",
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.4",
    "hexo-deployer-git": "^0.3.0",
    "hexo-filter-mermaid": "^1.0.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it-plus": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-mermaid": "^1.0.0",
    "hexo-wordcount": "^3.0.2",
    "path": "^0.12.7",
    "puppeteer": "^1.1.1"
  },
  "devDependencies": {}
}
```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [x] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
mobile_layout_economy: true
auto_excerpt: enable: true
```

**Comment by sli1989** [comment] 2018-03-18 04:02
Why i can't reproduce this bug today? ...

**Comment by ivan-nginx** [comment] 2018-03-18 04:03
Need to enable this option:
```yml
# Automatically Excerpt. Not recommend.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 150
```

**Comment by sli1989** [comment] 2018-03-18 04:18
Caused by `mobile_layout_economy: true`... I got it wrong.

**Comment by ivan-nginx** [comment] 2018-03-18 04:21
This bug only can be catched in homepage with autoexerpt option — all eutoexerpt text can't have CSS styles for left-right paddings/margins, so, text will be in full width. In mobile style, of course.

**Comment by sli1989** [comment] 2018-03-18 04:26
But `mobile_layout_economy: false` & `auto_excerpt: enable: true` works fine.

**Comment by ivan-nginx** [comment] 2018-03-18 04:27
Yes. And `mobile_layout_economy: true` & `auto_excerpt: enable: true` works not fine. This issue releated for this.

**Comment by GARENFEATHER** [comment] 2018-03-18 16:30
@sli1989 sorry, I temporarily return back to `mobile_layout_economy: false`  now, the bug is comfirmed by @ivan-nginx

**Comment by GARENFEATHER** [comment] 2018-03-23 02:32
weird……I set economy false an deploy it **so many times** ,but it return back to the bad margin style and fail to come back normal

**Comment by sli1989** [comment] 2018-03-23 02:39
Try in V6+?

**Comment by stevenjoezhang** [comment] 2018-12-25 03:51
Another bug is that ``` will be converted to `123456789101112131415161718` in post excerpt by content.substring(), which is mentioned in https://github.com/theme-next/hexo-theme-next/issues/333.

**Comment by ivan-nginx** [comment] 2019-03-16 12:04
It's same as in #696.

**Comment by stevenjoezhang** [comment] 2019-03-17 08:07
@ivan-nginx They're different. This bug is caused by missing `<p>` tag in post excerpt, and was already resolved.

**Closed** 2019-03-19 16:20 UTC
Labels: Bug, Solved, Verified
