### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by S-W-K** [theme-next/hexo-theme-next#1070] opened 2019-08-06 23:02 UTC
Add a multilingual button for switching the website into different language version(contents of different language must be separated).

**Comment by stevenjoezhang** [comment] 2019-08-11 04:08
Duplicate of #1069, #852

**Comment by stevenjoezhang** [comment] 2019-08-20 10:10
See also https://github.com/iissnan/hexo-theme-next/issues/1680

**Comment by jiangtj** [comment] 2019-09-27 01:40
Multi-language support, need to consider how to implement 🤔
Some users use multiple hexo sites, and add those to the menu, like @Liam0205 
https://liam.page/
Some add button to switch in post-meta, like me
https://www.dnocm.com/en/articles/beechnut/hexo-next-injects/

@S-W-K Which, or there are other ideas you prefer it?

**Comment by S-W-K** [comment] 2019-09-30 15:12
@jiangtj 
I prefer the former. But there's a problem that your Chinese posts and English posts are not totally separated. Both of those two kinds of posts will be archived and tagged together. This is my ideal design https://dengcb.com/zh/index.html

**Comment by stevenjoezhang** [comment] 2019-10-06 08:07
Does this plugin help: https://github.com/Jamling/hexo-generator-i18n

**Comment by Gabirel** [comment] 2019-10-15 13:14
@stevenjoezhang This plugin does not support the separation of contents of different languages. Also, it does not provide a language switcher button by default.

**Comment by stevenjoezhang** [comment] 2020-02-28 15:13
There is no extra space in the header, and in the Gemini / Pisces scheme, the sidebar is hidden on mobile. Therefore, the footer may be the only place to put this multilingual button.

<img width="1007" alt="截屏2020-02-28下午11 04 30" src="https://user-images.githubusercontent.com/16272760/75559795-0b96cc80-5a7f-11ea-8b83-6fdccb07c4e3.png">

**Comment by stevenjoezhang** [comment] 2020-02-28 16:09
However, multilingual processing still has difficulties: Hexo does not provide enough easy-to-use APIs. Multi-language on hexo.io relies on a custom helper instead of Hexo's built-in methods:
https://github.com/hexojs/site/blob/f205475980049069f768aca0ed13a2a3633f9189/scripts/helpers.js#L149-L152

**Comment by stevenjoezhang** [comment] 2020-02-29 05:18
Are you currently configuring multiple languages based on this document?
https://hexo.io/zh-cn/docs/internationalization

@S-W-K @Gabirel @njzjz

**Comment by stevenjoezhang** [comment] 2020-02-29 10:20
@S-W-K @Gabirel @njzjz

Checkout this PR: https://github.com/theme-next/hexo-theme-next/pull/1391

**Comment by stevenjoezhang** [comment] 2020-02-29 15:12
> Both of those two kinds of posts will be archived and tagged together.

> This plugin does not support the separation of contents of different languages. 

This feature is not as easy to implement as imagined. `hexo-generator-index` does not generate separate homepages for articles in different languages, which means that you must modify the configuration and execute Hexo generate multiple times to correctly generate multilingual website.

I researched the implementation of hexo-theme-minos and found that the core plugins of Hexo have been rewritten: https://github.com/ppoffice/hexo-theme-minos/commit/f0269850ab83fba1200457c40d9e59c49a027fe4
Obviously this is beyond the responsibility of the theme NexT.
#1391 is all the features that theme NexT can implement now. If you would like to simplify the generation of multilingual websites, please ask Hexo for help: http://github.com/hexojs/hexo/issues

**Closed by stevenjoezhang** 2020-02-29 15:12 UTC
Labels: Feature Request, 🎯 Roadmap

**Comment by stevenjoezhang** [comment] 2020-03-18 10:44
Added in #1391

If you need full multi-language support, please submit an issue in Hexo's repository. Thanks!
