### ISSUE TITLE
导航路径错误

### ISSUE THREAD

**Issue by github-amazingboy** [theme-next/hexo-theme-next#604] opened 2019-02-10 14:09 UTC
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
windows 10 上，菜单路径如果用\ 则导航菜单不能选中，如果只用一个 \tags 则切换导航时候会变成\tags\about\。 用了 \ debug 没有大问题，但是在执行 hexo g 后，生成页面的css路径错误, 比如：
http://xxx.com/tags/node/ 的样式引用是  link rel="stylesheet" href="../css/main.css?v=7.0.0"  ,应该是 ../../css/main.css 才对吧

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.12.0
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```
### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  home: \ || home
  about: \about || user
  tags: \tags || tags
  categories: \categories || th
  archives: \archives || archive
```

**Comment by JiangTJ** [comment] 2019-02-10 14:55
Try this:
```yaml
menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
```
I also use win10. :smile:

**Comment by github-amazingboy** [comment] 2019-02-11 13:14
> Try this:
> 
> ```yaml
> menu:
>   home: / || home
>   about: /about/ || user
>   tags: /tags/ || tags
>   categories: /categories/ || th
>   archives: /archives/ || archive
> ```
> 
> I also use win10. 😄

I try it , the nav link cannot work, I find the link with not a "href" attribute in the source .

**Comment by JiangTJ** [comment] 2019-02-12 04:03
Can you provide source code?

**Comment by tiannian** [comment] 2019-02-12 07:29
@github-amazingboy  I got the same problems.
First, the menu's element loses "href" attribute.
Second, the css file's path of all pages is prefixed by '../' .
I guess this problem caused by `url_for` function, but I dont know how to fix them.

**Comment by tiannian** [comment] 2019-02-12 07:36
It will work well when I visit pages in `hexo server` , but the static files generated by `hexo` will be broken.

**Comment by JiangTJ** [comment] 2019-02-12 07:38
@tiannian Try `hexo clean` before `hexo g`.

**Comment by tiannian** [comment] 2019-02-12 07:49
I tried, but no help.
```
<link rel="stylesheet" href="../css/main.css?v=7.0.0"/>
<link rel="apple-touch-icon" sizes="180x180" href="../images/logo.jpg?v=7.0.0">
<link rel="icon" type="image/png" sizes="32x32" href="../images/logo.jpg?v=7.0.0">
<link rel="icon" type="image/png" sizes="16x16" href="../images/logo.jpg?v=7.0.0">
<link rel="mask-icon" href="../images/logo.jpg?v=7.0.0" color="#222">
```
This code copy from `index.html` .

**Comment by JiangTJ** [comment] 2019-02-12 08:06
@tiannian Sorry, I can't reproduce.... Orz
![default](https://user-images.githubusercontent.com/15902347/52620540-cdfceb00-2edf-11e9-93c3-08631235872d.png)
I checkout tag 7.0, but it seems well

**Comment by tiannian** [comment] 2019-02-12 08:14
@JiangTJ Your picture has inspired me. I solved this problem.
@github-amazingboy Check the config item called `relative_link` in `_config.yaml` and set false.

**Comment by tiannian** [comment] 2019-02-12 08:16
This configuration item may cause a problem for `url_for` function. Please note it. I think this is a bug.

**Comment by JiangTJ** [comment] 2019-02-12 08:37
I saw https://hexo.io/zh-cn/docs/templates#%E4%BC%98%E5%8C%96
![default](https://user-images.githubusercontent.com/15902347/52622104-f555b700-2ee3-11e9-8e96-5664a28527a8.png)
Fragment Caching is need in NexT to provide faster generate speed.
So maybe won't fixed.

@github-amazingboy same issue?

**Comment by tiannian** [comment] 2019-02-12 08:43
Oh sorry, it's my fault. Don't care what i said. @JiangTJ ~\(≧▽≦)/~

**Comment by github-amazingboy** [comment] 2019-02-13 04:35
@JiangTJ  @tiannian  OH, sorry , i not read the document. i will close the issue.

**Comment by stevenjoezhang** [comment] 2019-08-28 15:34
@jiangtj Maybe we need to remind the user to set `relative_link` to `false` in the document? See also https://github.com/theme-next/hexo-theme-next/issues/1114

**Comment by jiangtj** [comment] 2019-08-28 16:02
在脚本里可以修改配置参数的，所以或许我们可以修改这个参数一直为false
We can modify the configuration parameter in the script, so maybe we can modify it to false all the time

**Comment by stevenjoezhang** [comment] 2019-08-28 16:04
Will there be any negative effects from `cache.enable: true`? Maybe we can force enable cache and set `relative_link: false` by default

**Comment by stevenjoezhang** [comment] 2019-09-01 16:04
@jiangtj @1v9 Checkout this brach: https://github.com/theme-next/hexo-theme-next/compare/rel
If the issue is resolved, merge it to master.

**Comment by jiangtj** [comment] 2019-09-02 03:31
![image](https://user-images.githubusercontent.com/15902347/64088622-ebf34580-cd74-11e9-9809-43ddbae994be.png)
It might be better to add a warning log to tell the user that `relative_link` has been set to false

**Comment by stevenjoezhang** [comment] 2019-09-02 03:43
https://github.com/theme-next/hexo-theme-next/commit/c27e18b168bbc915dfcd722efa43da7135cf6977

**Comment by jiangtj** [comment] 2019-09-02 05:22
> @jiangtj @1v9 Checkout this brach: https://github.com/theme-next/hexo-theme-next/compare/rel
> If the issue is resolved, merge it to master.

https://jiangtj.gitlab.io/next-test/gemini/    @stevenjoezhang No problem in my test site.

**Closed** 2019-09-02 07:36 UTC
Labels: Hexo, Improvement Need, 📖 Docs
