### ISSUE TITLE
给Pisces和Gemini主题的侧边栏增加一个在半屏时候可以显示的按钮

### ISSUE THREAD

**Issue by suyin-long** [theme-next/hexo-theme-next#1294] opened 2019-11-28 13:32 UTC
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**建议：**
Pisces和Gemini主题在电脑上半屏显示的时候，没有一个可以展开侧边栏(sidebar)的按钮，这就导致在半屏的时候想点击文章目录中的某一部分需要重新回到全屏下去点击，这就会比较麻烦。但是Muse和Mist主题在半屏显示的时候会有一个可以点击展开侧边栏的按钮，这样就可以随时通过这个按钮来随时点击侧边来，跳转到你想看的目录对应的地方，这个就比较方便。
希望可以给Pisces和Gemini主题也增加一个这样的按钮。

示意图：
Muse和Mist主题
![Muse和Mist主题](https://user-images.githubusercontent.com/49554285/69810240-67ef1380-1226-11ea-8dad-ef21bcecb266.png)

Pisces和Gemini主题
![Pisces和Gemini主题](https://user-images.githubusercontent.com/49554285/69810282-8228f180-1226-11ea-966d-5d0d401e77c5.png)

**Comment by stevenjoezhang** [comment] 2019-11-28 13:40
> I have already viewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

Duplicate of https://github.com/theme-next/hexo-theme-next/issues/281

说了多少次不要重复提交Issue还这样。我真诚地建议您使用其它主题，谢谢！

**Closed by stevenjoezhang** 2019-11-28 13:40 UTC
Labels: Feature Request
