### ISSUE TITLE
The underline of each link is connected into a piece

### ISSUE THREAD

**Issue by Mlearn** [theme-next/hexo-theme-next#824] opened 2019-04-09 08:28 UTC
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Show spaces between underline of each link.

### Actual behavior 
The underline of each link is connected into a piece

### Steps to reproduce the behavior 
![Snipaste_2019-04-09_16-13-18](https://user-images.githubusercontent.com/7379015/55784888-17367900-5ae4-11e9-8b75-be528cd2b80e.png)

### Node.js and NPM Information

```
PS D:\Users\xxx\Hexo_Blog> node -v
v11.0.0
PS D:\Users\xxx\Hexo_Blog> npm -v
6.4.1
PS D:\Users\xxx\Hexo_Blog>
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-addlink": "^1.0.4",
    "hexo-asset-image": "0.0.2",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
INFO  [hexo-math] Using engine 'mathjax'
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 11.0.0
v8: 7.0.276.28-node.5
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 67
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i

icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
INFO  neat the html: D:\Users\AM\Hexo_Blog\node_modules\hexo-math\asset\inject.swig [ 11.56% saved]
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
# Blog rolls
links_icon: link
links_title: Links
#links_layout: block
links_layout: inline
links:
  #Title: http://example.com
  V2EX: https://www.v2ex.com/?r=Exp
  宇宙的心弦: https://www.physixfan.com/
  MindHacks: http://mindhacks.cn/
  Matrix67: http://www.matrix67.com/blog/
  当然我在扯淡: http://www.yinwang.org/
  小强的时间管理博客: http://www.gtdlife.com/
```

**Comment by stevenjoezhang** [comment] 2019-04-09 09:33
Could you please provide an URL?
![屏幕快照 2019-04-09 下午5 32 29](https://user-images.githubusercontent.com/16272760/55789765-82387d80-5aed-11e9-8cb1-0b6762dd9858.png)

**Comment by Mlearn** [comment] 2019-04-09 16:01
> Could you please provide an URL?
> ![屏幕快照 2019-04-09 下午5 32 29](https://user-images.githubusercontent.com/16272760/55789765-82387d80-5aed-11e9-8cb1-0b6762dd9858.png)

www.anmou.me

**Comment by zq-97** [comment] 2019-04-10 01:35
@Mlearn That is because there is no space margin between `a` elements.
So two solutions.
# SOLUTION ONE
enable horizontal margin between elements, 
![选区_014](https://user-images.githubusercontent.com/17429111/55845275-cd956f00-5b73-11e9-80ee-e9a9c344ff31.png)
![选区_015](https://user-images.githubusercontent.com/17429111/55845289-dede7b80-5b73-11e9-964a-2bdb09ba749d.png)
# SOLUTION TWO
use `text decoration` instead of `boder bottom`
![选区_016](https://user-images.githubusercontent.com/17429111/55845300-e9007a00-5b73-11e9-9982-41a188a3a031.png)
![选区_017](https://user-images.githubusercontent.com/17429111/55845307-eb62d400-5b73-11e9-9660-ae08a80297e9.png)

**Comment by zq-97** [comment] 2019-04-10 01:52
<pre><font color="#00FF00"><b>zq@ASUS</b></font>:<font color="#5C5CFF"><b>~/blog/themes/next</b></font>$ git blame source/css/_mixins/Pisces.styl 
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  1) sidebar-inline-links-item() {
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  2)   margin: 5px 0 0;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  3)   if !hexo-config(&apos;social_icons.icons_only&apos;) { width: 50%; }
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  4) 
8a9b7e94 (ᴍɪᴍɪ       2019-03-17 01:36:25 +0800  5)   &amp; a, span.exturl {
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  6)     max-width: 216px;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  7)     box-sizing: border-box;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  8)     display: inline-block;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300  9)     margin-right: 0;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 10)     margin-bottom: 0;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 11)     padding: 0 5px;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 12)     overflow: hidden;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 13)     white-space: nowrap;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 14)     text-overflow: ellipsis;
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 15)   }
e12bb0b2 (Ivan.Nginx 2017-12-31 20:05:19 +0300 16) }
</pre>

This css code was committed in old `Next` repo, but I suspect there is a problem here.
you see, ` margin-bottom` together with `margin-bottom`, not a symmetry style, maybe an ancient bug?

**Comment by Mlearn** [comment] 2019-04-10 11:08
@zq-97 I don't know how to do it even if you told me. I just reported this bug and hope to be solved in the next release.

I am really not good at  web development.

thanks again.

**Comment by stevenjoezhang** [comment] 2019-04-10 12:04
@Mlearn Seems you're using NexT v7.1.0 . Can you try the latest version v7.2.0 and see if the bug still exist?

**Comment by zq-97** [comment] 2019-04-10 12:05
v7.2.0 released?

**Comment by stevenjoezhang** [comment] 2019-04-10 12:08
Ahh, not v7.2.0, I made a mistake...
![屏幕快照 2019-04-10 下午8 06 23](https://user-images.githubusercontent.com/16272760/55877293-43c5c000-5bcc-11e9-837d-71e9c0fa3670.png)

But I still can't reproduce the bug in master branch...

**Comment by zq-97** [comment] 2019-04-10 12:12
@Mlearn I think you should try v7.2.0 first. I have [a blog](https://i-m.dev/posts/20190331-103618.html) for quick update and deal with your site configuration.
If not work, try add this to `themes/next/source/css/_variables/custom.styl`?
```css
links-of-blogroll-list .links-of-blogroll-item a {
  margin-right: 5px;
}
```
if not work, use `margin-right: 5px !important;` and try again.

**Comment by zq-97** [comment] 2019-04-10 12:15
I thought you just released it seconds ago.
Since it's just a draft, try css directly.

**Comment by stevenjoezhang** [comment] 2019-04-10 12:26
@zq-97 You can compare these sites: https://www.anmou.me/ and https://zhangshuqiao.org/. The style of sidebar items are different, but the css looks the same.
It might be caused by css override, or default behaviour of some browsers? Or it was broken during the process of rebuild:
![屏幕快照 2019-04-10 下午8 23 33](https://user-images.githubusercontent.com/16272760/55878222-956f4a00-5bce-11e9-8b9f-1128b14f1b3c.png)


And, would you like to open a pull request to implement your solution?

**Comment by zq-97** [comment] 2019-04-10 13:18
I also though it's really strange because your two site has the **SAME** css style, and I view it on the same browser. Theoretically speaking it shouldn't be process build problem or browser problem.

Therefore I made a test by myself.
![image](https://user-images.githubusercontent.com/17429111/55881881-13831f00-5bd6-11e9-96e9-e0e9161b3c86.png)
Everything is OK with my test, I think we'd better find out the final reason before make any fix PR.

**Comment by zq-97** [comment] 2019-04-10 13:21
@Mlearn could you share your `# Blog rolls` configuration in `themes/next/_config`?

**Comment by Mlearn** [comment] 2019-04-11 08:50
@zq-97 I've just made a test based on the HEAD of master branch. 
The underline of each link keep apart in `scheme: Muse` mode, but is connected into a piece in `scheme: Gemini` mode. Nothing but `scheme` changed.
![Snipaste_2019-04-11_16-47-54](https://user-images.githubusercontent.com/7379015/55943810-dcfee000-5c79-11e9-8ded-6ca2c78f4ced.png)

**Comment by Mlearn** [comment] 2019-04-11 09:00
@zq-97 I found the reason. 

I've installed "hexo-neat": "^1.0.4", and turned it on in '_config.yml' file under the main hexo folder. Turning it off makes everything normal.

**Comment by zq-97** [comment] 2019-04-11 09:06
Maybe a preliminary conclusion.
It is caused by `neat` code reformat and style mixin problem? Very weird problem.

**Comment by Mlearn** [comment] 2019-04-11 09:13
@zq-97 Skills are limited, I can't go further.

**Comment by zq-97** [comment] 2019-04-11 09:23
So do I.
Maybe you can try it for temporary repaire before anyone fix this problem.
```
links-of-blogroll-list .links-of-blogroll-item a {
  margin-right: 5px;
}
```

**Closed** 2019-04-16 09:35 UTC
Labels: Question, Solved
