### ISSUE TITLE
Social Email-Link Doesn't working.

### ISSUE THREAD

**Issue by cyrilney** [theme-next/hexo-theme-next#1295] opened 2019-11-28 17:32 UTC
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

![image](https://user-images.githubusercontent.com/10266906/69824194-ffb02a00-1245-11ea-824b-fe4c2191143b.png)

socia.E-Mail 设置为 mailto:xxxx@gmail.com 后生成标签不能实现发邮件跳转，反而显示404

经查，a标签上地址为相对目录地址

        <a href="/mailto:cyrilnee2513@gmail.com" title="E-Mail → mailto:xxxxxx2513@gmail.com" rel="noopener" target="_blank"><i class="fa fa-fw fa-envelope"></i>E-Mail</a>

## Expected behavior 

出发mailto 跳转邮件客户端。

## Actual behavior 

404

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. clone主题
2. 启用social.E-Mail
3. 更改出题为next
4. 生成启动服务

### Node.js and NPM Information

```
node version: v10.12.0
npm version: 6.13.1
```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by stevenjoezhang** [comment] 2019-11-29 02:03
Duplicate of https://github.com/theme-next/hexo-theme-next/issues/1260
It's a bug of Hexo, fixed in hexojs/hexo-util#130

**Closed by stevenjoezhang** 2019-11-29 02:03 UTC
Labels: Bug
