### ISSUE TITLE
Lists in Mobile style have too far left margin.

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#736] opened 2019-03-26 13:06 UTC
Move the lists for some pixels to the left.
## Current

![image](https://user-images.githubusercontent.com/16944225/54999006-af563d80-4fcf-11e9-890e-865d25daa5e4.png)

## Expected

![image](https://user-images.githubusercontent.com/16944225/54999249-212e8700-4fd0-11e9-9e26-7d0ec95fd674.png)

**Comment by stevenjoezhang** [comment] 2019-03-26 13:26
Yes, mentioned in https://github.com/theme-next/hexo-theme-next/issues/721, caused by https://github.com/theme-next/hexo-theme-next/pull/669

**Comment by stevenjoezhang** [comment] 2019-03-29 12:14
Fixed in #752

**Closed by stevenjoezhang** 2019-03-29 12:14 UTC
Labels: Bug, Low Priority, Solved
