### ISSUE TITLE
Hexo theme NexT generate too much slower than default theme (landscape)

### ISSUE THREAD

**Issue by cocobear** [theme-next/hexo-theme-next#539] opened 2018-12-26 05:44 UTC
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
使用默认的主题landscape生成353篇文章只需要
$ ls source/_posts/ | wc -l
353
$ hexo clean && hexo g

> INFO  991 files generated in 12 s

### Actual behavior 
但使用了NexT主题（git clone 最新版本）， 配置文件为默认， 速度慢了很多：
$ ls source/_posts/ | wc -l
353
$ hexo clean && hexo g
> INFO  1018 files generated in 1.65 min

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v8.12.0
6.4.1

```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}

```

#### Hexo version

```
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
$ cat _config.yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 可可熊D窝
subtitle: Keep it simple, stupid
description: 爱折腾的技术宅一枚
keywords: cocobear blog python linux
author: cocobear
email: cocobear.cn@gmail.com
language: zh-CN

avatar: http://ww1.sinaimg.cn/small/72b1593dly1fyhtve330uj20ca0ca78u.jpg


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://cocobear.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    type: git
    repo: https://github.com/cocobear/cocobear.github.io.git
    branch: master

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by cocobear** [comment] 2018-12-26 06:57
By the way I have:
353 posts, 7 categories, 172 tags

**Comment by ivan-nginx** [comment] 2018-12-26 07:14
As i can see, your blog (https://c.js.org) use old 5.1.0 NexT version, which have slow generation speed, because have no `cache` option.
See [NexT v6.0.0 release notes](https://theme-next.org/next-6-0-0-released/) for more info.
And try to reproduce same behavior with clean NexT v6.x, i'm sure, generation speed will be faster.

**Comment by cocobear** [comment] 2018-12-26 07:41
> As i can see, your blog (https://c.js.org) use old 5.1.0 NexT version, which have slow generation speed, because have no `cache` option. See [NexT v6.0.0 release notes](https://theme-next.org/next-6-0-0-released/) for more info.
> And try to reproduce same behavior with clean NexT v6.x, i'm sure, generation speed will be faster.

my blog did use old 5.1.0 version. 
But I'm try to upgrade to the new NexT v6, above test is on the local computer.

I just make a test, try change NexT version to 5.1.0 the result is 

> INFO  1070 files generated in 29 s

nothing change , just change the NexT version to old 5.1.0

**Comment by ivan-nginx** [comment] 2018-12-26 07:45
Are you try to install **clean** version 6 & without any additional plugins? `cache` option must exists in new NexT config:

https://github.com/theme-next/hexo-theme-next/blob/24776f5fb84363310699a16098b6a41c94f9d2f1/_config.yml#L11-L13

**Comment by cocobear** [comment] 2018-12-26 07:51
Yes I get NexT 6 using command:
`git clone https://github.com/theme-next/hexo-theme-next themes/next`

**Comment by ivan-nginx** [comment] 2018-12-26 07:54
So? Can you check again generation speed (hexo clean && hexo g) with 5 and 6 versions? Speed is different or not?

**Comment by cocobear** [comment] 2018-12-26 08:05
The speed is different:
version 5
> INFO  1070 files generated in 28 s

version 6

> INFO  1019 files generated in 1.6 min

here is command output log:

[hexo_next_generate_test.log](https://github.com/theme-next/hexo-theme-next/files/2709769/hexo_next_generate_test.log)

**Comment by cocobear** [comment] 2018-12-27 03:55
Is there anything I can do to help resolve this bug?

**Comment by ivan-nginx** [comment] 2018-12-27 13:13
Yes, bugfix will be done ASAP.

**Comment by ivan-nginx** [comment] 2018-12-28 12:21
@cocobear check #545 pull. I think speed will better.

If solved, close it.

**Comment by cocobear** [comment] 2018-12-28 15:20
> @cocobear check #545 pull. I think speed will better.
> 
> If solved, close it.

Yes ！ It's much faster than before, about 3x faster on my notebook.

**Comment by stevenjoezhang** [comment] 2019-06-25 01:42
Discuss here: https://github.com/theme-next/hexo-theme-next/issues/661

**Closed by stevenjoezhang** 2019-06-25 01:42 UTC
Labels: Improvement Need, ☑ Verified
