### ISSUE TITLE
The lib resources of the website are all lost. I was upgraded from 5.1. I did not say how to set this resource on the document.

### ISSUE THREAD

**Issue by iiskei** [theme-next/hexo-theme-next#23] opened 2018-01-11 08:34 UTC
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Normal display of website
### Actual behavior 
Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/pace/pace-theme-minimal.min.css?v=1.0.2 Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/fancybox/source/jquery.fancybox.css?v=2.1.5 Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/Han/dist/han.min.css?v=3.3 Failed to load resource: the server responded with a status of 404 (Not Found)
pace.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/pace/pace-theme-minimal.min.css?v=1.0.2 Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/Han/dist/han.min.css?v=3.3 Failed to load resource: the server responded with a status of 404 (Not Found)
/lib/fancybox/source/jquery.fancybox.css?v=2.1.5 Failed to load resource: the server responded with a status of 404 (Not Found)
www.iskei.cn/:121 Uncaught SyntaxError: Unexpected token ,
jquery.fancybox.pack.js Failed to load resource: the server responded with a status of 404 (Not Found)
needsharebutton.js Failed to load resource: the server responded with a status of 404 (Not Found)
pace-theme-minimal.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
han.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.fancybox.css Failed to load resource: the server responded with a status of 404 (Not Found)
utils.js?v=6.0.1:3 Uncaught ReferenceError: NexT is not defined
    at utils.js?v=6.0.1:3

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml

```

**Comment by maple3142** [comment] 2018-01-11 12:04
Update instruction: [从 NexT v5.1.x 更新](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md)

**Comment by ivan-nginx** [comment] 2018-01-11 14:19
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

**Comment by liuli1735** [comment] 2018-01-14 02:11
6.01 依然有这个问题

**Comment by Blealtan** [comment] 2018-01-14 14:02
Seems to be issues caused by external plugins not installed. As proposed by Ivan, [Installing Plugins](https://github.com/theme-next/hexo-theme-next/blob/master/docs/INSTALLATION.md#plugins) has a great chance to help. If resolved, plz inform us or close this issue.

Also, @liuli1735 not all attendees here Chinese; speak English please. At least Ivan is not and knows no Chinese. Be open please.

**Comment by ivan-nginx** [comment] 2018-01-14 15:44
@Blealtan thank you.

**Closed** 2018-01-18 07:20 UTC
Labels: Resovled Maybe
